[project]
version = "0.0.0"
name = "unraid_api"
authors = [{ name = "chris-mc1" }]
description = "Unraid integration for Homeassistant"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = ["aiohttp>=3.11.13", "awesomeversion>=25.5.0"]
[project.urls]
Homepage = "https://github.com/chris-mc1/unraid_api"
Issues = "https://github.com/chris-mc1/unraid_api/issues"

[dependency-groups]
dev = [
    { include-group = "lint" },
    { include-group = "test" },
    "colorlog==6.12.0",
    "homeassistant==2026.8.1",
    "prek==0.5.1",
]
lint = ["ruff==0.16.5"]
test = ["pytest-homeassistant-custom-component"]

[tool.uv]
constraint-dependencies = ["cffi==2.0.0"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = ["if TYPE_CHECKING:"]

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
