name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ha-version: ["homeassistant==2026.9.0", "homeassistant==2026.9.1"]
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
      - run: uv run --with ${{ matrix.ha-version }} --with pytest-homeassistant-custom-component pytest
